export interface InstagramRequester {
  fetchOdCompany(producer: string, cookies: string): Promise<any[]>;
}
/*
const a = {
  data: [
    {
      taken_at: 1679374784,
      pk: '3063140166453353144',
      id: '3063140166453353144_698263952',
      device_timestamp: 1402810676449887,
      media_type: 1,
      code: 'CqCdcCOrtq4',
      client_cache_key: 'MzA2MzE0MDE2NjQ1MzM1MzE0NA==.2',
      filter_type: 0,
      is_unified_video: false,
      should_request_ads: false,
      commerciality_status: 'not_commercial',
      is_paid_partnership: false,
      is_visual_reply_commenter_notice_enabled: false,
      clips_tab_pinned_user_ids: [],
      has_delayed_metadata: false,
      comment_likes_enabled: true,
      comment_threading_enabled: true,
      max_num_visible_preview_comments: 2,
      has_more_comments: true,
      preview_comments: [],
      comments: [],
      comment_count: 95,
      can_view_more_preview_comments: false,
      hide_view_all_comment_entrypoint: false,
      inline_composer_display_condition: 'impression_trigger',
      user: [Object],
      can_viewer_reshare: true,
      like_count: 5087,
      has_liked: false,
      top_likers: [],
      facepile_top_likers: [],
      is_comments_gif_composer_enabled: true,
      image_versions2: [Object],
      original_width: 1440,
      original_height: 1440,
      accessibility_caption:
        'Photo by OD COMPANY 오디컴퍼니 on March 20, 2023. May be an image of 1 person.',
      photo_of_you: false,
      is_organic_product_tagging_eligible: false,
      can_see_insights_as_brand: false,
      caption: [Object],
      caption_is_edited: false,
      highlight_post_metadata: null,
      coauthor_producers: null,
      coauthor_producer_can_see_organic_insights: null,
      group: null,
      is_groups_post_pending_admin_approval: null,
      invited_coauthor_producers: null,
      guide_metadata: null,
      comment_inform_treatment: [Object],
      sharing_friction_info: [Object],
      original_media_has_visual_reply_media: false,
      like_and_view_counts_disabled: false,
      can_viewer_save: true,
      is_in_profile_grid: false,
      profile_grid_control_enabled: false,
      attribution: null,
      organic_tracking_token:
        'eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjp0cnVlLCJ1dWlkIjoiMjcwY2Y3ZGI4NjcxNDI3MTg3MzdiZjY3ODI5M2MzMGYzMDYzMTQwMTY2NDUzMzUzMTQ0Iiwic2VydmVyX3Rva2VuIjoiMTY4MTAyNTM1OTkzMHwzMDYzMTQwMTY2NDUzMzUzMTQ0fDQ3MzQ3NjIyNTQ4fDMyM2Q4YmQ5ZTZkY2I1NGJiOTdiYjY1NWJlMTljZDU2ZmU5Zjg1OTVhZWRlNDA0YmEwYWU4ZGExY2NjZjhiYWQifSwic2lnbmF0dXJlIjoiIn0=',
      has_shared_to_fb: 0,
      product_type: 'feed',
      show_shop_entrypoint: false,
      deleted_reason: 0,
      integrity_review_decision: 'pending',
      commerce_integrity_review_decision: '',
      music_metadata: [Object],
      is_artist_pick: false,
      ig_media_sharing_disabled: false,
    },
  ],
  num_results: 23,
  more_available: true,
  next_max_id: '3063140166453353144_698263952',
  user: {
    pk: '698263952',
    pk_id: '698263952',
    username: 'od_musical',
    full_name: 'OD COMPANY 오디컴퍼니',
    is_private: false,
    is_verified: true,
    profile_pic_id: '3053756392712095151_698263952',
    profile_pic_url:
      'https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-19/334487740_616059900371369_5077464731057217911_n.jpg?stp=dst-jpg_s150x150&_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_cat=105&_nc_ohc=xkkWA4uiYgwAX8FL0Zq&edm=ACWDqb8BAAAA&ccb=7-5&oh=00_AfBKnTSPUnwsWwVZU6cVQWYBckxkMXTwJZTO9AWKD4iEWA&oe=6437CFCE&_nc_sid=1527a3',
    profile_grid_display_type: 'default',
  },
  auto_load_more_enabled: false,
  status: 'ok',
};
*/
